### ISSUE TITLE
can't run protractor from eclipse

### ISSUE THREAD

**Issue by Shrewdtechs** [FinalDevStudio/fi-fileman#3]
(node:14292) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[14:01:55] I/launcher - Running 1 instances of WebDriver
[14:01:55] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[14:01:56] E/launcher - Error code: 135
[14:01:56] E/launcher - Error message: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:4444
[14:01:56] E/launcher - Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:4444
    at ClientRequest.<anonymous> (C:\Users\ShajibuM\eclipse-workspace\Shavi1\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:238:15)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\Users\ShajibuM\eclipse-workspace\Shavi1\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:769:24)
    at Function.createSession (C:\Users\ShajibuM\eclipse-workspace\Shavi1\node_modules\protractor\node_modules\selenium-webdriver\chrome.js:761:15)
    at createDriver (C:\Users\ShajibuM\eclipse-workspace\Shavi1\node_modules\protractor\node_modules\selenium-webdriver\index.js:170:33)
    at Builder.build (C:\Users\ShajibuM\eclipse-workspace\Shavi1\node_modules\protractor\node_modules\selenium-webdriver\index.js:626:16)
    at Hosted.getNewDriver (C:\Users\ShajibuM\eclipse-workspace\Shavi1\node_modules\protractor\built\driverProviders\driverProvider.js:53:33)
    at Runner.createBrowser (C:\Users\ShajibuM\eclipse-workspace\Shavi1\node_modules\protractor\built\runner.js:195:43)
    at q.then.then (C:\Users\ShajibuM\eclipse-workspace\Shavi1\node_modules\protractor\built\runner.js:339:29)
    at _fulfilled (C:\Users\ShajibuM\eclipse-workspace\Shavi1\node_modules\protractor\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\ShajibuM\eclipse-workspace\Shavi1\node_modules\protractor\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\ShajibuM\eclipse-workspace\Shavi1\node_modules\protractor\node_modules\q\q.js:796:13)
[14:01:56] E/launcher - Process exited with error code 135

**Comment by stgogm** [comment]
Hi! This should be fixed in v2.2.1. Can you confirm that you're using that version?

**Comment by stgogm** [comment]
@Shrewdtechs Please let me know if you're still having this issue or if it can be closed. Thanks!

**Comment by stgogm** [comment]
@Shrewdtechs It's been more than a week without an answer so I'll be closing this issue. If you have any further issues we'll be glad to help! Cheers!
